spring.application.name=Peliculas

# ========== BASE DE DATOS ==========
spring.datasource.url=jdbc:mysql://localhost:3306/basepelis
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========== JPA / HIBERNATE ==========
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ========== PUERTO ==========
server.port=8080

# ========== SWAGGER / OPENAPI ==========
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.show-actuator=false

# token

app.jwt-secret=c2VjcmV0b211eWxhcmdveWNvbXBsZWpvZGViZXNlcmVzdGUxMjM0NTY3ODkwYWJjZGVmZ2hpag==
app.jwt-expiration-milliseconds=86400000